<a href="https://colab.research.google.com/github/SHsix/Embedded_System/blob/master/lec02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 모듈 불러오기

In [0]:
import numpy as np

# Python List -> Numpy 배열
#### size - 배열의 크기, dtype - 배열 원소의 타입
#### Python List와 같이 index 접근이 가능합니다

In [4]:
list = [1, 2, 3]
Array = np.array(list)

print(Array)
print(Array.size)
print(Array.dtype)
print(Array[1])

[1 2 3]
3
int64
2


# 배열 초기화
#### np.zeros -> 모든 값 0으로 초기화
#### np.ones -> 모든 값 1로 초기화
#### np.random.randint(0, 9, (3, 3)) -> 0 ~ 9 범위 내 (3, 3) 배열 생성

In [5]:
arr1 = np.zeros((4, 4))
print(arr1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
arr2 = np.ones((3,3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
arr3 = np.random.randint(0, 9, (3, 3))
print(arr3)

[[0 1 8]
 [4 8 7]
 [3 4 5]]


# 배열 합치기
![title](img/figure2.png)