<a href="https://colab.research.google.com/github/SHsix/Embedded_System/blob/master/Python_%EA%B8%B0%EC%B4%88/lec02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 모듈 불러오기

In [0]:
import numpy as np

# Python List -> Numpy 배열
#### size - 배열의 크기, dtype - 배열 원소의 타입
#### Python List와 같이 index 접근이 가능합니다

In [0]:
list = [1, 2, 3]
Array = np.array(list)

print(Array)
print(Array.size)
print(Array.dtype)
print(Array[1])

[1 2 3]
3
int64
2


# 배열 초기화
#### np.zeros -> 모든 값 0으로 초기화
#### np.ones -> 모든 값 1로 초기화
#### np.random.randint(0, 9, (3, 3)) -> 0 ~ 9 범위 내 (3, 3) 배열 생성

In [0]:
arr1 = np.zeros((4, 4))
print(arr1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
arr2 = np.ones((3,3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [0]:
arr3 = np.random.randint(0, 9, (3, 3))
print(arr3)

[[0 1 8]
 [4 8 7]
 [3 4 5]]


# 배열 합치기 & 배열 Shape변환
![title](https://github.com/SHsix/Embedded_System/blob/master/Python_%EA%B8%B0%EC%B4%88/img/figure2.png?raw=1)
####배열 합치기 : np.concatenate
####배열 Shape : np.reshape

In [8]:
array1 = np.array([1, 2])
array2 = np.array([3, 4])
array3 = np.concatenate([array1, array2])
print(array3)
print(array3.shape)
array3 = array3.reshape(2, 2)
print(array3)

[1 2 3 4]
(4,)
[[1 2]
 [3 4]]
